package se.inix.homeassistantviewer.ui.theme

import androidx.compose.ui.graphics.Color

// Vibrant Light Theme Colors
val primaryLight = Color(0xFF006782)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFBCE9FF)
val onPrimaryContainerLight = Color(0xFF001F29)
val secondaryLight = Color(0xFF4C626C)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCFE6F2)
val onSecondaryContainerLight = Color(0xFF071E27)
val tertiaryLight = Color(0xFF5A5B7E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE0E0FF)
val onTertiaryContainerLight = Color(0xFF161837)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFBFCFE)
val onBackgroundLight = Color(0xFF191C1E)
val surfaceLight = Color(0xFFFBFCFE)
val onSurfaceLight = Color(0xFF191C1E)
val surfaceVariantLight = Color(0xFFDBE4E9)
val onSurfaceVariantLight = Color(0xFF40484C)

// Vibrant Dark Theme Colors
val primaryDark = Color(0xFF62D2FF)
val onPrimaryDark = Color(0xFF003544)
val primaryContainerDark = Color(0xFF004D62)
val onPrimaryContainerDark = Color(0xFFBCE9FF)
val secondaryDark = Color(0xFFB3CAD5)
val onSecondaryDark = Color(0xFF1E333C)
val secondaryContainerDark = Color(0xFF354A53)
val onSecondaryContainerDark = Color(0xFFCFE6F2)
val tertiaryDark = Color(0xFFC3C3EA)
val onTertiaryDark = Color(0xFF2C2D4D)
val tertiaryContainerDark = Color(0xFF424465)
val onTertiaryContainerDark = Color(0xFFE0E0FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF191C1E)
val onBackgroundDark = Color(0xFFE1E2E4)
val surfaceDark = Color(0xFF191C1E)
val onSurfaceDark = Color(0xFFE1E2E4)
val surfaceVariantDark = Color(0xFF40484C)
val onSurfaceVariantDark = Color(0xFFDBE4E9)
